.build_script: &build_script
  script:
    - mkdir shared
    - cd shared
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make VERBOSE=1
    - ctest -V
    - cd ..
    - mkdir static
    - cd static
    - cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC_LLVM_DISAS=ON ..
    - make VERBOSE=1
    - ctest -V

.build_artifacts: &build_artifacts
  artifacts:
    paths:
      - shared/libllvm-disas.so
      - shared/test-app
      - static/libllvm-disas.a
      - static/test-app
    when: always

linux:
  image: debian:latest
  before_script:
    - apt update
    - apt install -y cmake g++ xz-utils
  <<: *build_script
  <<: *build_artifacts
