image: debian:stretch

before_script:
  - apt update
  - apt install -y cmake g++ xz-utils

build:
  script:
    - cmake .
    - make

  artifacts:
    paths:
      - libllvm.so
      - main
    when: always
