image: debian:stretch

before_script:
  - apt update
  - apt install -y cmake g++ xz-utils

build:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make VERBOSE=1

  artifacts:
    paths:
      - build/libLLVM.so
      - build/test-app
    when: always
