image: debian:stretch

before_script:
  - apt update
  - apt install -y cmake g++ xz-utils

build:
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make VERBOSE=1
    - ctest -V

  artifacts:
    paths:
      - build/libLLVM.so
      - build/test-app
    when: always
